### ISSUE TITLE
Module is declared with using 'export =' error

### ISSUE THREAD

**Issue by mariourban83** [lukaskupczyk/ngx-super-croppie#13]
Hi there, the plugin worked fine before,  but after upgrading to Angular 13, I keep getting error in the console :

![Screen Shot 2023-03-07 at 17 15 40](https://user-images.githubusercontent.com/49397106/223498274-b81b132d-4636-409c-880a-67a6775194a9.png)

The problem doesn't go away even if allowSyntheticDefaultImports: true in tsconfig.json is set.

Can you help please?

**Comment by lukaskupczyk** [comment]
I suppose this issue wasn't connected to ngx-super-croppie?
