### ISSUE TITLE
Make the width property in the boundary as optional

### ISSUE THREAD

**Issue by gilballesca** [lukaskupczyk/ngx-super-croppie#20]
Is there's any way that we can make the boundary declaration into optional, 
especially the boundary: { width: number, height: number }

so if nothing is declared for the width, the boundary will inherit the width from the parent dom. especially if the parent element is using an alignment content to center or any position. 

Thanks..

**Comment by lukaskupczyk** [comment]
As we are only referencing the croppy options you could just not set a boundary at all, e.g.

```typescript
  public croppieOptions: CroppieOptions = {
    customClass: 'my-class',
    enableExif: true,
    enableOrientation: true,
    enableZoom: true,
    enforceBoundary: true,
    enableResize: false,
    maxZoom: 1,
    minZoom: 0,
    mouseWheelZoom: true,
    showZoomer: true,
    viewport: { width: 200, height: 200, type: 'circle' },
  };
```

I hope this answers your question.
