### ISSUE TITLE
Angular 18+ Support

### ISSUE THREAD

**Issue by beetsauce** [lukaskupczyk/ngx-super-croppie#21]
We recently caught up on some much needed tech debt and updated our application to Angular 17, which puts us well within the LTS window until next May. At some point between now and then, we will want to bump up to Angular 18. Any chance there will be a new version to support this upgrade?

**Comment by lukaskupczyk** [comment]
The latest version 18.0.0 supports angular 18.

**Comment by beetsauce** [comment]
Awesome! Thank you!
